config/routes.rb
Rails.application.routes.draw do
  get 'cvs/new'

  get 'cvs/create'

  get 'cvs/index'

  get 'cvs/edit'

  get 'regions/list'

  get 'user_profiles/new'

  get 'user_profiles/update'

  get 'user_profiles/show'

  root to: 'sessions#new'
  get 'sessions/new'

  # Users routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # Sessions managing
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:country_id/regions', to: 'regions#list'

  resources :users do
    resources :cvs

    get   '/profile', to: 'user_profiles#new'
    post  '/profile', to: 'user_profiles#create'
    patch '/update',  to: 'users#update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/custom_section.rb
class CustomSection < ApplicationRecord
  belongs_to :user
end

app/models/cv.rb
class Cv < ApplicationRecord
  belongs_to :user
  has_many :cv_sections
end

app/models/cv_section.rb
class CvSection < ApplicationRecord
  belongs_to :user
  belongs_to :cv
  belongs_to :section
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  before_save { email.downcase! }

  has_many :cv_sections
  has_many :cvs
  has_one  :user_profile
  has_many :custom_sections

  has_secure_password
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def edit
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def list
    @results = Region.where(country_code: params[:country_id]).map{ |x| x.name }
    render :json => @results
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @user_profile = @user.user_profile
  end

  def create
    @user = User.find(params[:user_id])
    @user_profile = @user.build_user_profile(user_profile_params)
    if @user_profile.save
      flash[:success] = "Your profile info was succesfully updated."
      redirect_to @user
    else
      flash[:error] = "#{@user_profile.errors.keys[0].to_s} #{@user_profile.errors.values[0][0]}".capitalize
      redirect_to user_profile_path(@user)
    end
  end

  def update
    @user = User.find(params[:user_id])
  end

  def show
    @user = User.find(params[:user_id])
  end

  private

    def user_profile_params
      params.require(:user_profile).permit(:second_name, :other_names,
                                           :address_1, :address_2, :postcode,
                                           :land_phone, :country_code,
                                           :area_code, :city_code)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(user_params)
      flash[:success] = "User info updated succesfully."
      redirect_to user_profile_path(@user)
    else
      flash[:error] = "#{@user.errors.keys[0].to_s} #{@user.errors.values[0][0]}".capitalize
      redirect_to user_profile_path(@user)
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Your account was succesfully created."
      redirect_to @user
    else
      render 'new'
    end
  end


  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :phone_prefix, :first_name, :last_names, :mobile_phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title = '')
    base_title = "CV Builder"

    if title.empty?
      base_title
    else
      "#{title} | #{base_title}"
    end
  end
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def user_location(user)
    if user.present? && user.user_profile.present?
      code = user.user_profile.country_code
      city = user.user_profile.city_code
      country = code.present? ? Country.where(code: code).first.name : ''
      return "#{city}, #{country}".strip()
    end
    ''
  end

  def user_cvs_count(user)
    if user.present?
      count = user.cvs.count
      return "#{pluralize(count, 'created CV')}"
    end
  end

  def user_sections_count(user)
    if user.present?
      count = user.cv_sections.count
      return "#{pluralize(count, 'filled section')}"
    end
  end

  def user_custom_sections_count(user)
    if user.present?
      count = user.custom_sections.count
      return "#{pluralize(count, 'custom section')}"
    end
  end
end

app/views/cvs/_no_cvs.html.erb
<div class="row justify-content-md-center pt-5">
  <div class="col-md-6 text-center no-cvs-container">
    <h1>Create as many CVs and Resumes as you want, for free</h1>
    <div class="col-md-8 offset-md-2 new-cv">
      <span class="icon-file1"></span>
      <h6>Create your first CV</h6>
    </div>
  </div>
</div>

app/views/cvs/create.html.erb
<h1>Cvs#create</h1>
<p>Find me in app/views/cvs/create.html.erb</p>

app/views/cvs/edit.html.erb
<h1>Cvs#edit</h1>
<p>Find me in app/views/cvs/edit.html.erb</p>

app/views/cvs/index.html.erb
<h1>Cvs#index</h1>
<p>Find me in app/views/cvs/index.html.erb</p>

app/views/cvs/new.html.erb
<h1>Cvs#new</h1>
<p>Find me in app/views/cvs/new.html.erb</p>

app/views/user_profiles/_form.html.erb
<%= form_for(:user_profile) do |f| %>
  <%= f.label :second_name %>
  <%= f.text_field :second_name, class: 'form-control form-input' %>

  <%= f.label :other_names %>
  <%= f.text_field :other_names, class: 'form-control form-input' %>

  <%= f.label :address_1, 'Address' %>
  <%= f.text_field :address_1, class: 'form-control form-input' %>

  <%= f.label :address_2, 'Address Line 2' %>
  <%= f.text_field :address_2, class: 'form-control form-input' %>

  <%= f.label :postcode %>
  <%= f.text_field :postcode, class: 'form-control form-input' %>

  <%= f.label :land_phone, 'Phone' %>
  <%= f.text_field :land_phone, class: 'form-control form-input' %>

  <%= f.label :country_code, 'Country' %>
  <%= f.collection_select :country_code, Country.all, :code, :name, {include_blank: 'Select'}, {class: 'form-control form-input'} %>

  <%= f.label :area_code, 'Area' %>
  <%= f.collection_select :area_code, [], :name, :name, {include_blank: true}, {class: 'form-control form-input', disabled: 'true'} %>

  <%= f.label :city_code, 'City' %>
  <%= f.text_field :city_code, class: 'form-control form-input' %>

  <%= f.submit "Save changes", class: 'btn form-input form-button' %>
<% end %>

app/views/user_profiles/new.html.erb
<% provide(:title, "Profile") %>
<div class="row justify-content-md-center pt-4">
  <div class="col-md-6">
    <h2>Basic Info</h2>
    <%= render partial: 'users/form', locals: {user: @user} %>
    <br />
    <h2>Additional information</h2>
    <%= render partial: 'form', locals: {user_profile: @account} %>
  </div>
</div>

app/views/user_profiles/show.html.erb
<h1>UserProfiles#show</h1>
<p>Find me in app/views/user_profiles/show.html.erb</p>

app/views/user_profiles/update.html.erb
<h1>UserProfiles#update</h1>
<p>Find me in app/views/user_profiles/update.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(:user, :url => user_update_path(:user), method: "patch", remote: true, html: { id: 'update-profile-form', :data_type => 'json'}) do |f| %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control form-input' %>

  <%= f.label :first_name %>
  <%= f.text_field :first_name, class: 'form-control form-input' %>

  <%= f.label :last_names %>
  <%= f.text_field :last_names, class: 'form-control form-input' %>

  <%= f.label :mobile_phone %>
  <div class="form-row">
    <div class="col-3">
      <%= f.select(:phone_prefix, [['(+1)', '+1'], ['(+57)', '+57']], {}, {class: 'form-control form-input'}) %>
    </div>
    <div class="col-9">
      <%= f.text_field :mobile_phone, class: 'form-control form-input' %>
    </div>
  </div>

  <%= f.submit 'Save changes', class: 'btn form-input form-button' %>

<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="row justify-content-md-center top-spaced">
  <div class="col-md-6">
    <h1>Sign up</h1>
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control form-input" %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control form-input" %>

      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control form-input" %>

      <%= f.submit "Sign Up", class: "btn form-input form-button" %>

      <%= link_to "Log in", login_path, class: "signup-link" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Home') %>
<div class="row pt-2">
  <div class="col-md-8 offset-md-1">
    <% if @user.cvs.blank? %>
      <%= render partial: 'cvs/no_cvs' %>
    <% else %>
      <%= render partial: 'cvs/list' %>
    <% end %>
  </div>
  <div class="col-md-3 basic-info">
    <h5><%= @user.first_name %> <%= @user.last_names %></h5>
    <hr />
    <p><%= user_cvs_count(@user) %></p>
    <p><%= user_sections_count(@user) %></p>
    <p><%= user_custom_sections_count(@user) %></p>
  </div>
</div>