config/routes.rb
Rails.application.routes.draw do
  get 'cvs/new'

  get 'cvs/create'

  get 'cvs/index'

  get 'cvs/edit'

  get 'regions/list'

  get 'user_profiles/new'

  get 'user_profiles/update'

  get 'user_profiles/show'

  root to: 'sessions#new'
  get 'sessions/new'

  # Users routes
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # Sessions managing
  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/:country_id/regions', to: 'regions#list'

  resources :users do
    resources :cvs

    get   '/profile', to: 'user_profiles#new'
    post  '/profile', to: 'user_profiles#create'
    patch '/update',  to: 'users#update'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/custom_section.rb
class CustomSection < ApplicationRecord
  belongs_to :user
end

app/models/cv.rb
class Cv < ApplicationRecord
  belongs_to :user
  has_many :cv_sections
end

app/models/cv_section.rb
class CvSection < ApplicationRecord
  belongs_to :user
  belongs_to :cv
  belongs_to :section
end

app/models/region.rb
class Region < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  before_save { email.downcase! }

  has_many :cv_sections
  has_many :cvs
  has_one  :user_profile
  has_many :custom_sections

  has_secure_password
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def edit
  end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  def list
    @results = Region.where(country_code: params[:country_id]).map{ |x| x.name }
    render :json => @results
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def update
    @user = User.find(session[:user_id])
    if @user.update_attributes(user_params)
      flash[:success] = "User info updated succesfully."
      redirect_to user_profile_path(@user)
    else
      flash[:error] = "#{@user.errors.keys[0].to_s} #{@user.errors.values[0][0]}".capitalize
      redirect_to user_profile_path(@user)
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      flash[:success] = "Your account was succesfully created."
      redirect_to @user
    else
      render 'new'
    end
  end


  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :phone_prefix, :first_name, :last_names, :mobile_phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def page_title(title = '')
    base_title = "CV Builder"

    if title.empty?
      base_title
    else
      "#{title} | #{base_title}"
    end
  end
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def user_location(user)
    if user.present? && user.user_profile.present?
      code = user.user_profile.country_code
      city = user.user_profile.city_code
      country = code.present? ? Country.where(code: code).first.name : ''
      return "#{city}, #{country}".strip()
    end
    ''
  end

  def user_cvs_count(user)
    if user.present?
      count = user.cvs.count
      return "#{pluralize(count, 'created CV')}"
    end
  end

  def user_sections_count(user)
    if user.present?
      count = user.cv_sections.count
      return "#{pluralize(count, 'filled section')}"
    end
  end

  def user_custom_sections_count(user)
    if user.present?
      count = user.custom_sections.count
      return "#{pluralize(count, 'custom section')}"
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark navbar-expand-md">
  <a class="navbar-brand" href="#">Open Résumé</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto mr-2">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'My CVs', user_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Account', user_profile_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', logout_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', login_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign up', signup_path, class: 'nav-link' %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Open Resume</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <div class="container-fluid main-container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type == 'error' ? 'danger' : message_type %>"><%= message %> </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div>
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>